ktor:
  application:
    modules:
      - io.liftgate.bus.dataflow.ApplicationKt.module
  deployment:
    port: 2550

api:
  # use openssl rand -base64 48 to generate a new auth token. used for API req auth
  auth-token: "J7a/YClg6ju40+pCvmYMNB3wFCtwraT07wItEFhTrTzhjTGY5g36uHLNd2nzKFyQ"

mongo:
  connection-uri: "mongodb://localhost"
  database: "transport-dataflow"

bus:
  trans-loc:
    agency: 16
    api-key: "__NONE__"
    api-host: "transloc-api-1-2.p.rapidapi.com"
  # how long the GET Vehicles stay cached for
  cache-invalidation: 15000
