ktor:
  application:
    modules:
      - io.liftgate.bus.dataflow.ApplicationKt.module
  deployment:
    port: 8080

mongo:
  connection-uri: "mongodb://localhost"
  database: "transport-dataflow"
  collection: "eventlog"

bus:
  trans-loc:
    agency: 16
    api-key: "__NONE__"
    api-host: "transloc-api-1-2.p.rapidapi.com"
  # how long the GET Vehicles stay cached for
  cache-invalidation: 15000
